@{
    RootModule        = 'Loom.psm1'
    ModuleVersion     = '0.4.0'
    GUID              = 'a8c0e2f4-7b91-4d3e-9f06-2c1a5b8d4e70'
    Author            = 'Metra'
    CompanyName       = 'IWU'
    Copyright         = '(c) Metra'
    Description       = 'Loom: governed plan execution — queue, journal, triage, runner.'
    PowerShellVersion = '5.1'
    FunctionsToExport = @(
        'Invoke-LoomCommand'
        'Get-LoomStatusCatalog'
        'Get-LoomActiveTransitions'
        'Get-LoomRoutingContext'
        'Test-LoomRoutingAdapterAvailable'
        'Test-LoomCaptureAdapterAvailable'
        'Test-LoomContract'
        'Invoke-LoomInspectAdapter'
        'Invoke-LoomVerifyAdapter'
        'Get-LoomHostRoot'
        'Get-MetraLoomSchemaVersion'
        'Get-MetraLoomRoot'
        'Resolve-MetraLoomRoot'
        'Get-MetraLoomMinimumRoutingConfidence'
        'Get-MetraLoomPhaseATransitions'
        'Test-MetraLoomTransition'
        'Initialize-MetraLoomLayout'
        'Get-MetraLoomState'
        'Save-MetraLoomState'
        'Get-MetraLoomJournalPath'
        'Add-MetraLoomJournalEntry'
        'Get-MetraLoomJournalEntries'
        'Test-MetraLoomItemId'
        'Resolve-MetraLoomItemPath'
        'Get-MetraLoomQueueItemPath'
        'Get-MetraLoomQueueItems'
        'Get-MetraLoomQueueItem'
        'Save-MetraLoomQueueItem'
        'Test-MetraLoomQueueItemSchema'
        'New-MetraLoomQueueId'
        'New-MetraLoomCandidateId'
        'Invoke-MetraLoomStateChange'
        'Get-MetraLoomPlanRoots'
        'Get-MetraLoomFormalPlans'
        'Read-MetraLoomPlanFile'
        'Resolve-MetraLoomPlanProject'
        'Measure-MetraLoomTriageScore'
        'Test-MetraLoomEligibility'
        'Save-MetraLoomCandidate'
        'Get-MetraLoomCandidate'
        'Add-MetraLoomQueueItem'
        'New-MetraLoomQueueItemFromCandidate'
        'Invoke-MetraLoomTriage'
        'Invoke-MetraLoomEnqueueFromPlan'
        'Invoke-MetraLoomDailyStub'
        'Invoke-MetraLoomDailyBuild'
        'Invoke-MetraLoomDailyPackDiff'
        'Invoke-MetraLoomDailyApprove'
        'Read-LoomDailyPlanDirectives'
        'Test-LoomProjectAcceptanceGate'
        'Get-LoomSlice5Transitions'
        'Get-LoomProjectKey'
        'Invoke-MetraLoomRun'
        'Invoke-MetraLoomReview'
        'Invoke-MetraLoomMigrate'
        'Get-LoomActiveTransitionMap'
        'Write-LoomAtomicUtf8Text'
        'Get-LoomUtf8NoBomEncoding'
        'Test-LoomPathWithinRoot'
        'Test-LoomExecutionBranchPrefix'
    )
    AliasesToExport   = @()
    CmdletsToExport   = @()
    VariablesToExport = @()
    PrivateData       = @{
        PSData = @{
            Tags = @('Metra', 'Loom', 'governance')
        }
    }
}
